version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile.dev
        environment:
            - POSTGRES_USER=sasdemo
            - POSTGRES_PASSWORD=Orion123
            - POSTGRES_DB=example
            - PGDATA=/data
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "8080:5432" 